#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org
# Copyright (C) 2017 BG5HHP
. /usr/sbin/mmdvm.common
# This script needs shadow-useradd and openssl-util installed currently

START=99

SERVICE_USE_PID=0

PKG_NAME=MMDVMHost
BIN_FILE=/usr/sbin/MMDVMHost
CONF_NAME=MMDVM.ini
CONF_FILE=/etc/${CONF_NAME}
TMP_CONF_FILE=/tmp/.MMDVM.ini.upd
PID_FILE=/tmp/mmdvmhost.pid
SERVER_URL='https://hamclub.net/openwrt/config'

do_update(){
  local CALL=$1
  local MAC=$2

  if [ -e /etc/openwrt_release ];then
    CALL=`uci get system.@system[0].hostname`
    MAC=`ifconfig eth0 | awk '/HWaddr/ { print $5 }'`
  else
    CALL=`hostname -s`
    MAC=`ifconfig |grep HWaddr |awk '{print $5}' |head -n 1`
  fi
  [ -z $CALL ] && echo "Error: Need CALLSIGN" && exit
  [ -z $MAC ] && echo "Warn: missing MAC!"

  echo CALL: ${CALL}, MAC: ${MAC}

  local REMOTE=${SERVER_URL}/${CALL}.${CONF_NAME}?mac=${MAC//:/}

  echo "GET ${REMOTE}..."
  rm -f ${TMP_CONF_FILE}
  wget -q  ${REMOTE} -O ${TMP_CONF_FILE}
  if [ $? -ne 0 ];then
    echo "Get remote config FAILED!"
    return 1
  fi

  local MD5_REMOTE=`${MD5_TOOL} ${TMP_CONF_FILE} |awk '{print $1}'`
  local MD5_LOCAL=empty
  [ -f $CONF_FILE ] && MD5_LOCAL=`${MD5_TOOL} ${CONF_FILE} |awk '{print $1}'`
  echo "L: ${MD5_LOCAL}"
  echo "R: ${MD5_REMOTE}"
  if [ "${MD5_LOCAL}" = "${MD5_REMOTE}" ];then
    echo "Config is not changed"
    return 0
  fi

  # finally overwrite the local configuration file
  echo "Updating ${CONF_FILE}..."
  cp -f ${TMP_CONF_FILE} ${CONF_FILE}
  [ $? -eq 0 ] || echo "Update failed!"
}

check_update() {
  echo "Updating config from network..."
  if [ $1 -eq 0 ];then
    $1=3
  fi

  local i=1
  # while [ $i -le $1 ];do
  #   i=$(($i+1))
  #   echo "Trying $(($i-1))...";
  #   do_update
  #   [ $? -ne 0 ] || return 0
  #   sleep 5
  # done
  while true; do
    echo "Trying $(($i))...";
    i=$(($i+1))
    do_update
    [ $? -ne 0 ] || return 0
    [ $i -le $1 ] || return 1
    sleep 5
  done
  return 1
}

do_start() {
  if [ -e ${CONF_FILE} ]; then
    ${BIN_FILE} ${CONF_FILE}
    echo "Starting..."
    sleep 3
    local PID=`pidof ${PKG_NAME}`
    if [ $? -eq 1 ]; then
        echo "Process does not exist, ${PKG_NAME} will not start."
        #rm ${CONF_FILE}
        return 1
    fi
    echo ${PID} >${PID_FILE}
    >&2 echo "${PKG_NAME} started"
  else
    >&2 echo "configuration file missing, ${PKG_NAME} will not start."
  fi
}

start() {
  check_enabled
  if [ $? -eq 0 ]; then
    >&2 echo "${PKG_NAME} is disabled"
    return 0
  fi
	check_running
  if [ $? -eq 0 ]; then
    return 0
  fi
  check_user && check_permission
  check_update 1
  do_start
}

stop() {
  if [ -e ${PID_FILE} ]; then
    local PID=`cat ${PID_FILE}`
    kill $PID > /dev/null 2>&1
    rm -f ${PID_FILE}
    echo "${PKG_NAME} stopped"
  else
    echo "${PKG_NAME} is not running"
  fi
  return 0
}

restart() {
  stop
  start
}

EXTRA_COMMANDS="update"
EXTRA_HELP="        update  Update the configurations from cloud"
update(){
  check_update 3
}
