#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org
# Copyright (C) 2018 BG5HHP@hamclub.net
. /usr/sbin/mmdvm.common

START=99

SERVICE_USE_PID=0

PKG_NAME=xlxd
BIN_FILE=/usr/sbin/xlxd
CONF_FILE=/etc/XLXD.ini
PID_FILE=/tmp/xlxd.pid

check_permission(){
  [ -d /etc/mmdvm ] && chown -R ${USER} /etc/mmdvm
  touch /var/log/xlxd.xml && chown ${USER} /var/log/xlxd.xml && echo "xlxd.xml permission fixed";
  if [ ! -d ${LOG_DIR} ]; then
    mkdir -m 755 -p ${LOG_DIR}
  fi
  chown -R ${USER} ${LOG_DIR}
  echo "Check permission OK"
}

do_start() {
  local _XLX_NAME
  #read name from config
  if [ -e /etc/openwrt_release ];then
    _XLX_NAME=$(uci -q get mmdvm.@${PKG_NAME}[0].name)
  fi
  if [ -z $_XLX_NAME ];then
    _XLX_NAME="XLX999"
  fi

  if [ -e ${CONF_FILE} ]; then
    ${BIN_FILE} _XLX_NAME 0.0.0.0 127.0.0.1
    echo "Starting..."
    sleep 3
    PID=`pidof ${PKG_NAME}`
    if [ $? -eq 1 ]; then
        echo "Process does not exist, ${PKG_NAME} will not start."
        #rm ${CONF_FILE}
        exit 1
    fi
    echo ${PID} >${PID_FILE}
    >&2 echo "${PKG_NAME} started"
  else
    >&2 echo "configuration file missing, ${PKG_NAME} will not start."
  fi
}

start() {
  check_enabled
  if [ $? -eq 0 ]; then
    return 0
  fi  
	check_running
  if [ $? -eq 0 ]; then
    return 0
  fi
  #check_update 3
  check_user        
  do_start
}

stop() {
	if [ -e ${PID_FILE} ]; then
		PID=`cat ${PID_FILE}`
		kill $PID > /dev/null 2>&1
		rm -f ${PID_FILE}
		echo "${PKG_NAME} stopped"
	else
		echo "${PKG_NAME} is not running"
	fi
    return 0
}

restart() {
	stop
	start
}

#reload(){
#  update
#  if [ $? -ne 0 ];then
#	echo "Update config failed.";
#  else
#	stop
#	do_start
#	break
#  fi
#}
