#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org
# Copyright (C) 2017,2018 BG5HHP
. /usr/sbin/mmdvm.common

START=99

SERVICE_USE_PID=0


PKG_NAME=YSFGateway
BIN_FILE=/usr/sbin/YSFGateway
CONF_FILE=/etc/YSFGateway.ini
PID_FILE=/tmp/ysfgateway.pid

do_start() {
  if [ -e ${CONF_FILE} ]; then
    ${BIN_FILE} ${CONF_FILE}
    echo "Starting..."
    sleep 3
    PID=`pidof ${PKG_NAME}`
    if [ $? -eq 1 ]; then
        echo "Process does not exist, ${PKG_NAME} will not start."
        #rm ${CONF_FILE}
        exit 1
    fi
    echo ${PID} >${PID_FILE}
    >&2 echo "${PKG_NAME} started"
  else
    >&2 echo "configuration file missing, ${PKG_NAME} will not start."
  fi
}

start() {
  check_enabled
  if [ $? -eq 0 ]; then
    >&2 echo "${PKG_NAME} is disabled"
    return 0
  fi
	check_running
  if [ $? -eq 0 ]; then
    return 0
  fi
  #check_update 3
  check_user        
  do_start
}

stop() {
	if [ -e ${PID_FILE} ]; then
		PID=`cat ${PID_FILE}`
		kill $PID > /dev/null 2>&1
		rm -f ${PID_FILE}
		echo "${PKG_NAME} stopped"
	else
		echo "${PKG_NAME} is not running"
	fi
    return 0
}

restart() {
	stop
	start
}

#reload(){
#  update
#  if [ $? -ne 0 ];then
#	echo "Update config failed.";
#  else
#	stop
#	do_start
#	break
#  fi
#}
